name: project2
description: A starting point for Dart libraries or applications.
version: 1.0.0
environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  json2yaml: ^1.0.1+1
  project1:
    git:
      url: https://github.com/kalluriramkumar/demo-multi-proj.git
      path: project1
      ref: main

dependency_overrides:
  project1:
    path: ../project1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0